/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as FlyingSelfHireRouteImport } from './routes/flying/self-hire'
import { Route as FlyingLearnToFlyRouteImport } from './routes/flying/learn-to-fly'
import { Route as FlyingExperienceRouteImport } from './routes/flying/experience'
import { Route as CmsUsersRouteImport } from './routes/cms/users'
import { Route as CmsTeamRouteImport } from './routes/cms/team'
import { Route as CmsContentRouteImport } from './routes/cms/content'
import { Route as BookingDashboardRouteImport } from './routes/booking/dashboard'
import { Route as BookingAdminRouteImport } from './routes/booking/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const FlyingSelfHireRoute = FlyingSelfHireRouteImport.update({
  id: '/flying/self-hire',
  path: '/flying/self-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyingLearnToFlyRoute = FlyingLearnToFlyRouteImport.update({
  id: '/flying/learn-to-fly',
  path: '/flying/learn-to-fly',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyingExperienceRoute = FlyingExperienceRouteImport.update({
  id: '/flying/experience',
  path: '/flying/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsUsersRoute = CmsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CmsRoute,
} as any)
const CmsTeamRoute = CmsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CmsRoute,
} as any)
const CmsContentRoute = CmsContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => CmsRoute,
} as any)
const BookingDashboardRoute = BookingDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BookingRoute,
} as any)
const BookingAdminRoute = BookingAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BookingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/booking/admin': typeof BookingAdminRoute
  '/booking/dashboard': typeof BookingDashboardRoute
  '/cms/content': typeof CmsContentRoute
  '/cms/team': typeof CmsTeamRoute
  '/cms/users': typeof CmsUsersRoute
  '/flying/experience': typeof FlyingExperienceRoute
  '/flying/learn-to-fly': typeof FlyingLearnToFlyRoute
  '/flying/self-hire': typeof FlyingSelfHireRoute
  '/cms/': typeof CmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/booking/admin': typeof BookingAdminRoute
  '/booking/dashboard': typeof BookingDashboardRoute
  '/cms/content': typeof CmsContentRoute
  '/cms/team': typeof CmsTeamRoute
  '/cms/users': typeof CmsUsersRoute
  '/flying/experience': typeof FlyingExperienceRoute
  '/flying/learn-to-fly': typeof FlyingLearnToFlyRoute
  '/flying/self-hire': typeof FlyingSelfHireRoute
  '/cms': typeof CmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/booking/admin': typeof BookingAdminRoute
  '/booking/dashboard': typeof BookingDashboardRoute
  '/cms/content': typeof CmsContentRoute
  '/cms/team': typeof CmsTeamRoute
  '/cms/users': typeof CmsUsersRoute
  '/flying/experience': typeof FlyingExperienceRoute
  '/flying/learn-to-fly': typeof FlyingLearnToFlyRoute
  '/flying/self-hire': typeof FlyingSelfHireRoute
  '/cms/': typeof CmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/cms'
    | '/contact'
    | '/fleet'
    | '/privacy'
    | '/terms'
    | '/booking/admin'
    | '/booking/dashboard'
    | '/cms/content'
    | '/cms/team'
    | '/cms/users'
    | '/flying/experience'
    | '/flying/learn-to-fly'
    | '/flying/self-hire'
    | '/cms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/fleet'
    | '/privacy'
    | '/terms'
    | '/booking/admin'
    | '/booking/dashboard'
    | '/cms/content'
    | '/cms/team'
    | '/cms/users'
    | '/flying/experience'
    | '/flying/learn-to-fly'
    | '/flying/self-hire'
    | '/cms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/cms'
    | '/contact'
    | '/fleet'
    | '/privacy'
    | '/terms'
    | '/booking/admin'
    | '/booking/dashboard'
    | '/cms/content'
    | '/cms/team'
    | '/cms/users'
    | '/flying/experience'
    | '/flying/learn-to-fly'
    | '/flying/self-hire'
    | '/cms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRouteWithChildren
  CmsRoute: typeof CmsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  FlyingExperienceRoute: typeof FlyingExperienceRoute
  FlyingLearnToFlyRoute: typeof FlyingLearnToFlyRoute
  FlyingSelfHireRoute: typeof FlyingSelfHireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/flying/self-hire': {
      id: '/flying/self-hire'
      path: '/flying/self-hire'
      fullPath: '/flying/self-hire'
      preLoaderRoute: typeof FlyingSelfHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flying/learn-to-fly': {
      id: '/flying/learn-to-fly'
      path: '/flying/learn-to-fly'
      fullPath: '/flying/learn-to-fly'
      preLoaderRoute: typeof FlyingLearnToFlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flying/experience': {
      id: '/flying/experience'
      path: '/flying/experience'
      fullPath: '/flying/experience'
      preLoaderRoute: typeof FlyingExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/users': {
      id: '/cms/users'
      path: '/users'
      fullPath: '/cms/users'
      preLoaderRoute: typeof CmsUsersRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/team': {
      id: '/cms/team'
      path: '/team'
      fullPath: '/cms/team'
      preLoaderRoute: typeof CmsTeamRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/content': {
      id: '/cms/content'
      path: '/content'
      fullPath: '/cms/content'
      preLoaderRoute: typeof CmsContentRouteImport
      parentRoute: typeof CmsRoute
    }
    '/booking/dashboard': {
      id: '/booking/dashboard'
      path: '/dashboard'
      fullPath: '/booking/dashboard'
      preLoaderRoute: typeof BookingDashboardRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/admin': {
      id: '/booking/admin'
      path: '/admin'
      fullPath: '/booking/admin'
      preLoaderRoute: typeof BookingAdminRouteImport
      parentRoute: typeof BookingRoute
    }
  }
}

interface BookingRouteChildren {
  BookingAdminRoute: typeof BookingAdminRoute
  BookingDashboardRoute: typeof BookingDashboardRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingAdminRoute: BookingAdminRoute,
  BookingDashboardRoute: BookingDashboardRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

interface CmsRouteChildren {
  CmsContentRoute: typeof CmsContentRoute
  CmsTeamRoute: typeof CmsTeamRoute
  CmsUsersRoute: typeof CmsUsersRoute
  CmsIndexRoute: typeof CmsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsContentRoute: CmsContentRoute,
  CmsTeamRoute: CmsTeamRoute,
  CmsUsersRoute: CmsUsersRoute,
  CmsIndexRoute: CmsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRouteWithChildren,
  CmsRoute: CmsRouteWithChildren,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  FlyingExperienceRoute: FlyingExperienceRoute,
  FlyingLearnToFlyRoute: FlyingLearnToFlyRoute,
  FlyingSelfHireRoute: FlyingSelfHireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
