/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestAdminRouteImport } from './routes/request-admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as BookingIndexRouteImport } from './routes/booking/index'
import { Route as FlyingSelfHireRouteImport } from './routes/flying/self-hire'
import { Route as FlyingLearnToFlyRouteImport } from './routes/flying/learn-to-fly'
import { Route as FlyingExperienceRouteImport } from './routes/flying/experience'
import { Route as CmsUsersRouteImport } from './routes/cms/users'
import { Route as CmsTeamRouteImport } from './routes/cms/team'
import { Route as CmsStudentsRouteImport } from './routes/cms/students'
import { Route as CmsSelfHireApprovalsRouteImport } from './routes/cms/self-hire-approvals'
import { Route as CmsResourceBlocksRouteImport } from './routes/cms/resource-blocks'
import { Route as CmsPromotionsRouteImport } from './routes/cms/promotions'
import { Route as CmsMockPaymentsRouteImport } from './routes/cms/mock-payments'
import { Route as CmsFlyingStatusRouteImport } from './routes/cms/flying-status'
import { Route as CmsFleetRouteImport } from './routes/cms/fleet'
import { Route as CmsExpiriesRouteImport } from './routes/cms/expiries'
import { Route as CmsContentRouteImport } from './routes/cms/content'
import { Route as CmsClosedDatesRouteImport } from './routes/cms/closed-dates'
import { Route as CmsCalendarSettingsRouteImport } from './routes/cms/calendar-settings'
import { Route as CmsBookingsRouteImport } from './routes/cms/bookings'
import { Route as CmsBookingProductsRouteImport } from './routes/cms/booking-products'
import { Route as CmsAnalyticsRouteImport } from './routes/cms/analytics'
import { Route as CmsSplatRouteImport } from './routes/cms/$'
import { Route as BookingDashboardRouteImport } from './routes/booking/dashboard'
import { Route as BookingAdminRouteImport } from './routes/booking/admin'
import { Route as CmsStudentsStudentIdRouteImport } from './routes/cms/students.$studentId'
import { Route as BookingConfirmIdRouteImport } from './routes/booking/confirm.$id'
import { Route as BookingCheckoutIdRouteImport } from './routes/booking/checkout.$id'
import { Route as BookingBookSlugRouteImport } from './routes/booking/book.$slug'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAdminRoute = RequestAdminRouteImport.update({
  id: '/request-admin',
  path: '/request-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingRoute,
} as any)
const FlyingSelfHireRoute = FlyingSelfHireRouteImport.update({
  id: '/flying/self-hire',
  path: '/flying/self-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyingLearnToFlyRoute = FlyingLearnToFlyRouteImport.update({
  id: '/flying/learn-to-fly',
  path: '/flying/learn-to-fly',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyingExperienceRoute = FlyingExperienceRouteImport.update({
  id: '/flying/experience',
  path: '/flying/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsUsersRoute = CmsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CmsRoute,
} as any)
const CmsTeamRoute = CmsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CmsRoute,
} as any)
const CmsStudentsRoute = CmsStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CmsRoute,
} as any)
const CmsSelfHireApprovalsRoute = CmsSelfHireApprovalsRouteImport.update({
  id: '/self-hire-approvals',
  path: '/self-hire-approvals',
  getParentRoute: () => CmsRoute,
} as any)
const CmsResourceBlocksRoute = CmsResourceBlocksRouteImport.update({
  id: '/resource-blocks',
  path: '/resource-blocks',
  getParentRoute: () => CmsRoute,
} as any)
const CmsPromotionsRoute = CmsPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => CmsRoute,
} as any)
const CmsMockPaymentsRoute = CmsMockPaymentsRouteImport.update({
  id: '/mock-payments',
  path: '/mock-payments',
  getParentRoute: () => CmsRoute,
} as any)
const CmsFlyingStatusRoute = CmsFlyingStatusRouteImport.update({
  id: '/flying-status',
  path: '/flying-status',
  getParentRoute: () => CmsRoute,
} as any)
const CmsFleetRoute = CmsFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => CmsRoute,
} as any)
const CmsExpiriesRoute = CmsExpiriesRouteImport.update({
  id: '/expiries',
  path: '/expiries',
  getParentRoute: () => CmsRoute,
} as any)
const CmsContentRoute = CmsContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => CmsRoute,
} as any)
const CmsClosedDatesRoute = CmsClosedDatesRouteImport.update({
  id: '/closed-dates',
  path: '/closed-dates',
  getParentRoute: () => CmsRoute,
} as any)
const CmsCalendarSettingsRoute = CmsCalendarSettingsRouteImport.update({
  id: '/calendar-settings',
  path: '/calendar-settings',
  getParentRoute: () => CmsRoute,
} as any)
const CmsBookingsRoute = CmsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CmsRoute,
} as any)
const CmsBookingProductsRoute = CmsBookingProductsRouteImport.update({
  id: '/booking-products',
  path: '/booking-products',
  getParentRoute: () => CmsRoute,
} as any)
const CmsAnalyticsRoute = CmsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CmsRoute,
} as any)
const CmsSplatRoute = CmsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CmsRoute,
} as any)
const BookingDashboardRoute = BookingDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BookingRoute,
} as any)
const BookingAdminRoute = BookingAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BookingRoute,
} as any)
const CmsStudentsStudentIdRoute = CmsStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => CmsStudentsRoute,
} as any)
const BookingConfirmIdRoute = BookingConfirmIdRouteImport.update({
  id: '/confirm/$id',
  path: '/confirm/$id',
  getParentRoute: () => BookingRoute,
} as any)
const BookingCheckoutIdRoute = BookingCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => BookingRoute,
} as any)
const BookingBookSlugRoute = BookingBookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => BookingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/booking': typeof BookingRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request-admin': typeof RequestAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/booking/admin': typeof BookingAdminRoute
  '/booking/dashboard': typeof BookingDashboardRoute
  '/cms/$': typeof CmsSplatRoute
  '/cms/analytics': typeof CmsAnalyticsRoute
  '/cms/booking-products': typeof CmsBookingProductsRoute
  '/cms/bookings': typeof CmsBookingsRoute
  '/cms/calendar-settings': typeof CmsCalendarSettingsRoute
  '/cms/closed-dates': typeof CmsClosedDatesRoute
  '/cms/content': typeof CmsContentRoute
  '/cms/expiries': typeof CmsExpiriesRoute
  '/cms/fleet': typeof CmsFleetRoute
  '/cms/flying-status': typeof CmsFlyingStatusRoute
  '/cms/mock-payments': typeof CmsMockPaymentsRoute
  '/cms/promotions': typeof CmsPromotionsRoute
  '/cms/resource-blocks': typeof CmsResourceBlocksRoute
  '/cms/self-hire-approvals': typeof CmsSelfHireApprovalsRoute
  '/cms/students': typeof CmsStudentsRouteWithChildren
  '/cms/team': typeof CmsTeamRoute
  '/cms/users': typeof CmsUsersRoute
  '/flying/experience': typeof FlyingExperienceRoute
  '/flying/learn-to-fly': typeof FlyingLearnToFlyRoute
  '/flying/self-hire': typeof FlyingSelfHireRoute
  '/booking/': typeof BookingIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/booking/book/$slug': typeof BookingBookSlugRoute
  '/booking/checkout/$id': typeof BookingCheckoutIdRoute
  '/booking/confirm/$id': typeof BookingConfirmIdRoute
  '/cms/students/$studentId': typeof CmsStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request-admin': typeof RequestAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/booking/admin': typeof BookingAdminRoute
  '/booking/dashboard': typeof BookingDashboardRoute
  '/cms/$': typeof CmsSplatRoute
  '/cms/analytics': typeof CmsAnalyticsRoute
  '/cms/booking-products': typeof CmsBookingProductsRoute
  '/cms/bookings': typeof CmsBookingsRoute
  '/cms/calendar-settings': typeof CmsCalendarSettingsRoute
  '/cms/closed-dates': typeof CmsClosedDatesRoute
  '/cms/content': typeof CmsContentRoute
  '/cms/expiries': typeof CmsExpiriesRoute
  '/cms/fleet': typeof CmsFleetRoute
  '/cms/flying-status': typeof CmsFlyingStatusRoute
  '/cms/mock-payments': typeof CmsMockPaymentsRoute
  '/cms/promotions': typeof CmsPromotionsRoute
  '/cms/resource-blocks': typeof CmsResourceBlocksRoute
  '/cms/self-hire-approvals': typeof CmsSelfHireApprovalsRoute
  '/cms/students': typeof CmsStudentsRouteWithChildren
  '/cms/team': typeof CmsTeamRoute
  '/cms/users': typeof CmsUsersRoute
  '/flying/experience': typeof FlyingExperienceRoute
  '/flying/learn-to-fly': typeof FlyingLearnToFlyRoute
  '/flying/self-hire': typeof FlyingSelfHireRoute
  '/booking': typeof BookingIndexRoute
  '/cms': typeof CmsIndexRoute
  '/booking/book/$slug': typeof BookingBookSlugRoute
  '/booking/checkout/$id': typeof BookingCheckoutIdRoute
  '/booking/confirm/$id': typeof BookingConfirmIdRoute
  '/cms/students/$studentId': typeof CmsStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/booking': typeof BookingRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request-admin': typeof RequestAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/booking/admin': typeof BookingAdminRoute
  '/booking/dashboard': typeof BookingDashboardRoute
  '/cms/$': typeof CmsSplatRoute
  '/cms/analytics': typeof CmsAnalyticsRoute
  '/cms/booking-products': typeof CmsBookingProductsRoute
  '/cms/bookings': typeof CmsBookingsRoute
  '/cms/calendar-settings': typeof CmsCalendarSettingsRoute
  '/cms/closed-dates': typeof CmsClosedDatesRoute
  '/cms/content': typeof CmsContentRoute
  '/cms/expiries': typeof CmsExpiriesRoute
  '/cms/fleet': typeof CmsFleetRoute
  '/cms/flying-status': typeof CmsFlyingStatusRoute
  '/cms/mock-payments': typeof CmsMockPaymentsRoute
  '/cms/promotions': typeof CmsPromotionsRoute
  '/cms/resource-blocks': typeof CmsResourceBlocksRoute
  '/cms/self-hire-approvals': typeof CmsSelfHireApprovalsRoute
  '/cms/students': typeof CmsStudentsRouteWithChildren
  '/cms/team': typeof CmsTeamRoute
  '/cms/users': typeof CmsUsersRoute
  '/flying/experience': typeof FlyingExperienceRoute
  '/flying/learn-to-fly': typeof FlyingLearnToFlyRoute
  '/flying/self-hire': typeof FlyingSelfHireRoute
  '/booking/': typeof BookingIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/booking/book/$slug': typeof BookingBookSlugRoute
  '/booking/checkout/$id': typeof BookingCheckoutIdRoute
  '/booking/confirm/$id': typeof BookingConfirmIdRoute
  '/cms/students/$studentId': typeof CmsStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/booking'
    | '/cms'
    | '/contact'
    | '/fleet'
    | '/login'
    | '/privacy'
    | '/request-admin'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/booking/admin'
    | '/booking/dashboard'
    | '/cms/$'
    | '/cms/analytics'
    | '/cms/booking-products'
    | '/cms/bookings'
    | '/cms/calendar-settings'
    | '/cms/closed-dates'
    | '/cms/content'
    | '/cms/expiries'
    | '/cms/fleet'
    | '/cms/flying-status'
    | '/cms/mock-payments'
    | '/cms/promotions'
    | '/cms/resource-blocks'
    | '/cms/self-hire-approvals'
    | '/cms/students'
    | '/cms/team'
    | '/cms/users'
    | '/flying/experience'
    | '/flying/learn-to-fly'
    | '/flying/self-hire'
    | '/booking/'
    | '/cms/'
    | '/booking/book/$slug'
    | '/booking/checkout/$id'
    | '/booking/confirm/$id'
    | '/cms/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/fleet'
    | '/login'
    | '/privacy'
    | '/request-admin'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/booking/admin'
    | '/booking/dashboard'
    | '/cms/$'
    | '/cms/analytics'
    | '/cms/booking-products'
    | '/cms/bookings'
    | '/cms/calendar-settings'
    | '/cms/closed-dates'
    | '/cms/content'
    | '/cms/expiries'
    | '/cms/fleet'
    | '/cms/flying-status'
    | '/cms/mock-payments'
    | '/cms/promotions'
    | '/cms/resource-blocks'
    | '/cms/self-hire-approvals'
    | '/cms/students'
    | '/cms/team'
    | '/cms/users'
    | '/flying/experience'
    | '/flying/learn-to-fly'
    | '/flying/self-hire'
    | '/booking'
    | '/cms'
    | '/booking/book/$slug'
    | '/booking/checkout/$id'
    | '/booking/confirm/$id'
    | '/cms/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/booking'
    | '/cms'
    | '/contact'
    | '/fleet'
    | '/login'
    | '/privacy'
    | '/request-admin'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/booking/admin'
    | '/booking/dashboard'
    | '/cms/$'
    | '/cms/analytics'
    | '/cms/booking-products'
    | '/cms/bookings'
    | '/cms/calendar-settings'
    | '/cms/closed-dates'
    | '/cms/content'
    | '/cms/expiries'
    | '/cms/fleet'
    | '/cms/flying-status'
    | '/cms/mock-payments'
    | '/cms/promotions'
    | '/cms/resource-blocks'
    | '/cms/self-hire-approvals'
    | '/cms/students'
    | '/cms/team'
    | '/cms/users'
    | '/flying/experience'
    | '/flying/learn-to-fly'
    | '/flying/self-hire'
    | '/booking/'
    | '/cms/'
    | '/booking/book/$slug'
    | '/booking/checkout/$id'
    | '/booking/confirm/$id'
    | '/cms/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BookingRoute: typeof BookingRouteWithChildren
  CmsRoute: typeof CmsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestAdminRoute: typeof RequestAdminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  FlyingExperienceRoute: typeof FlyingExperienceRoute
  FlyingLearnToFlyRoute: typeof FlyingLearnToFlyRoute
  FlyingSelfHireRoute: typeof FlyingSelfHireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-admin': {
      id: '/request-admin'
      path: '/request-admin'
      fullPath: '/request-admin'
      preLoaderRoute: typeof RequestAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/booking/': {
      id: '/booking/'
      path: '/'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof BookingRoute
    }
    '/flying/self-hire': {
      id: '/flying/self-hire'
      path: '/flying/self-hire'
      fullPath: '/flying/self-hire'
      preLoaderRoute: typeof FlyingSelfHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flying/learn-to-fly': {
      id: '/flying/learn-to-fly'
      path: '/flying/learn-to-fly'
      fullPath: '/flying/learn-to-fly'
      preLoaderRoute: typeof FlyingLearnToFlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flying/experience': {
      id: '/flying/experience'
      path: '/flying/experience'
      fullPath: '/flying/experience'
      preLoaderRoute: typeof FlyingExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/users': {
      id: '/cms/users'
      path: '/users'
      fullPath: '/cms/users'
      preLoaderRoute: typeof CmsUsersRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/team': {
      id: '/cms/team'
      path: '/team'
      fullPath: '/cms/team'
      preLoaderRoute: typeof CmsTeamRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/students': {
      id: '/cms/students'
      path: '/students'
      fullPath: '/cms/students'
      preLoaderRoute: typeof CmsStudentsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/self-hire-approvals': {
      id: '/cms/self-hire-approvals'
      path: '/self-hire-approvals'
      fullPath: '/cms/self-hire-approvals'
      preLoaderRoute: typeof CmsSelfHireApprovalsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/resource-blocks': {
      id: '/cms/resource-blocks'
      path: '/resource-blocks'
      fullPath: '/cms/resource-blocks'
      preLoaderRoute: typeof CmsResourceBlocksRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/promotions': {
      id: '/cms/promotions'
      path: '/promotions'
      fullPath: '/cms/promotions'
      preLoaderRoute: typeof CmsPromotionsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/mock-payments': {
      id: '/cms/mock-payments'
      path: '/mock-payments'
      fullPath: '/cms/mock-payments'
      preLoaderRoute: typeof CmsMockPaymentsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/flying-status': {
      id: '/cms/flying-status'
      path: '/flying-status'
      fullPath: '/cms/flying-status'
      preLoaderRoute: typeof CmsFlyingStatusRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/fleet': {
      id: '/cms/fleet'
      path: '/fleet'
      fullPath: '/cms/fleet'
      preLoaderRoute: typeof CmsFleetRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/expiries': {
      id: '/cms/expiries'
      path: '/expiries'
      fullPath: '/cms/expiries'
      preLoaderRoute: typeof CmsExpiriesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/content': {
      id: '/cms/content'
      path: '/content'
      fullPath: '/cms/content'
      preLoaderRoute: typeof CmsContentRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/closed-dates': {
      id: '/cms/closed-dates'
      path: '/closed-dates'
      fullPath: '/cms/closed-dates'
      preLoaderRoute: typeof CmsClosedDatesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/calendar-settings': {
      id: '/cms/calendar-settings'
      path: '/calendar-settings'
      fullPath: '/cms/calendar-settings'
      preLoaderRoute: typeof CmsCalendarSettingsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/bookings': {
      id: '/cms/bookings'
      path: '/bookings'
      fullPath: '/cms/bookings'
      preLoaderRoute: typeof CmsBookingsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/booking-products': {
      id: '/cms/booking-products'
      path: '/booking-products'
      fullPath: '/cms/booking-products'
      preLoaderRoute: typeof CmsBookingProductsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/analytics': {
      id: '/cms/analytics'
      path: '/analytics'
      fullPath: '/cms/analytics'
      preLoaderRoute: typeof CmsAnalyticsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/$': {
      id: '/cms/$'
      path: '/$'
      fullPath: '/cms/$'
      preLoaderRoute: typeof CmsSplatRouteImport
      parentRoute: typeof CmsRoute
    }
    '/booking/dashboard': {
      id: '/booking/dashboard'
      path: '/dashboard'
      fullPath: '/booking/dashboard'
      preLoaderRoute: typeof BookingDashboardRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/admin': {
      id: '/booking/admin'
      path: '/admin'
      fullPath: '/booking/admin'
      preLoaderRoute: typeof BookingAdminRouteImport
      parentRoute: typeof BookingRoute
    }
    '/cms/students/$studentId': {
      id: '/cms/students/$studentId'
      path: '/$studentId'
      fullPath: '/cms/students/$studentId'
      preLoaderRoute: typeof CmsStudentsStudentIdRouteImport
      parentRoute: typeof CmsStudentsRoute
    }
    '/booking/confirm/$id': {
      id: '/booking/confirm/$id'
      path: '/confirm/$id'
      fullPath: '/booking/confirm/$id'
      preLoaderRoute: typeof BookingConfirmIdRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/checkout/$id': {
      id: '/booking/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/booking/checkout/$id'
      preLoaderRoute: typeof BookingCheckoutIdRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/book/$slug': {
      id: '/booking/book/$slug'
      path: '/book/$slug'
      fullPath: '/booking/book/$slug'
      preLoaderRoute: typeof BookingBookSlugRouteImport
      parentRoute: typeof BookingRoute
    }
  }
}

interface BookingRouteChildren {
  BookingAdminRoute: typeof BookingAdminRoute
  BookingDashboardRoute: typeof BookingDashboardRoute
  BookingIndexRoute: typeof BookingIndexRoute
  BookingBookSlugRoute: typeof BookingBookSlugRoute
  BookingCheckoutIdRoute: typeof BookingCheckoutIdRoute
  BookingConfirmIdRoute: typeof BookingConfirmIdRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingAdminRoute: BookingAdminRoute,
  BookingDashboardRoute: BookingDashboardRoute,
  BookingIndexRoute: BookingIndexRoute,
  BookingBookSlugRoute: BookingBookSlugRoute,
  BookingCheckoutIdRoute: BookingCheckoutIdRoute,
  BookingConfirmIdRoute: BookingConfirmIdRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

interface CmsStudentsRouteChildren {
  CmsStudentsStudentIdRoute: typeof CmsStudentsStudentIdRoute
}

const CmsStudentsRouteChildren: CmsStudentsRouteChildren = {
  CmsStudentsStudentIdRoute: CmsStudentsStudentIdRoute,
}

const CmsStudentsRouteWithChildren = CmsStudentsRoute._addFileChildren(
  CmsStudentsRouteChildren,
)

interface CmsRouteChildren {
  CmsSplatRoute: typeof CmsSplatRoute
  CmsAnalyticsRoute: typeof CmsAnalyticsRoute
  CmsBookingProductsRoute: typeof CmsBookingProductsRoute
  CmsBookingsRoute: typeof CmsBookingsRoute
  CmsCalendarSettingsRoute: typeof CmsCalendarSettingsRoute
  CmsClosedDatesRoute: typeof CmsClosedDatesRoute
  CmsContentRoute: typeof CmsContentRoute
  CmsExpiriesRoute: typeof CmsExpiriesRoute
  CmsFleetRoute: typeof CmsFleetRoute
  CmsFlyingStatusRoute: typeof CmsFlyingStatusRoute
  CmsMockPaymentsRoute: typeof CmsMockPaymentsRoute
  CmsPromotionsRoute: typeof CmsPromotionsRoute
  CmsResourceBlocksRoute: typeof CmsResourceBlocksRoute
  CmsSelfHireApprovalsRoute: typeof CmsSelfHireApprovalsRoute
  CmsStudentsRoute: typeof CmsStudentsRouteWithChildren
  CmsTeamRoute: typeof CmsTeamRoute
  CmsUsersRoute: typeof CmsUsersRoute
  CmsIndexRoute: typeof CmsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsSplatRoute: CmsSplatRoute,
  CmsAnalyticsRoute: CmsAnalyticsRoute,
  CmsBookingProductsRoute: CmsBookingProductsRoute,
  CmsBookingsRoute: CmsBookingsRoute,
  CmsCalendarSettingsRoute: CmsCalendarSettingsRoute,
  CmsClosedDatesRoute: CmsClosedDatesRoute,
  CmsContentRoute: CmsContentRoute,
  CmsExpiriesRoute: CmsExpiriesRoute,
  CmsFleetRoute: CmsFleetRoute,
  CmsFlyingStatusRoute: CmsFlyingStatusRoute,
  CmsMockPaymentsRoute: CmsMockPaymentsRoute,
  CmsPromotionsRoute: CmsPromotionsRoute,
  CmsResourceBlocksRoute: CmsResourceBlocksRoute,
  CmsSelfHireApprovalsRoute: CmsSelfHireApprovalsRoute,
  CmsStudentsRoute: CmsStudentsRouteWithChildren,
  CmsTeamRoute: CmsTeamRoute,
  CmsUsersRoute: CmsUsersRoute,
  CmsIndexRoute: CmsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BookingRoute: BookingRouteWithChildren,
  CmsRoute: CmsRouteWithChildren,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RequestAdminRoute: RequestAdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  FlyingExperienceRoute: FlyingExperienceRoute,
  FlyingLearnToFlyRoute: FlyingLearnToFlyRoute,
  FlyingSelfHireRoute: FlyingSelfHireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
